"use client";

import Image from "next/image";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { setActiveWorkspaceRole, useAuth } from "@/lib/auth-context";

type Role = "customer" | "worker" | "cooperative";
const roles: [Role, string, string][] = [["customer", "Customer", "Find services, book verified workers and manage requests."], ["worker", "Worker", "Find jobs, manage work and grow your skills."], ["cooperative", "Cooperative", "Manage workers, jobs, demand and cooperative operations."]];
const destination = (role: Role) => role === "worker" ? "/worker" : role === "cooperative" ? "/admin" : "/dashboard";

function Frame({ children, title, text }: { children: React.ReactNode; title: React.ReactNode; text: string }) {
  return <div className="min-h-screen bg-[#f4f9ff] text-[#0d1737]"><header className="border-b bg-white px-6 py-4"><div className="mx-auto flex max-w-[1440px] items-center justify-between"><Link href="/" className="text-3xl font-bold tracking-tight">Bridge<span className="text-blue-600">Point</span></Link><Link href="/" className="text-sm text-slate-600">Back to home</Link></div></header><main className="mx-auto grid max-w-[1440px] gap-10 px-6 py-10 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><section className="hidden lg:block"><span className="rounded-full bg-[#e5f1ff] px-5 py-2 text-xs text-slate-600">A cooperative-powered platform</span><h1 className="mt-7 text-6xl font-bold leading-[1.08]">{title}</h1><p className="mt-5 max-w-xl text-lg leading-7 text-slate-600">{text}</p><div className="mt-8 grid grid-cols-2 gap-4"><Image src="/community-workers.svg" alt="BridgePoint workers" width={300} height={180} className="h-44 w-full rounded-3xl object-cover" /><Image src="/hero-worker.svg" alt="Verified worker" width={300} height={180} className="h-44 w-full rounded-3xl object-cover" /></div><p className="mt-8 text-lg italic text-slate-600">“Work is not just a livelihood, it&apos;s a stronger tomorrow.”</p></section><section className="mx-auto w-full max-w-xl rounded-[28px] bg-white p-7 shadow-xl md:p-10">{children}</section></main><footer className="border-t bg-white px-6 py-7 text-sm text-slate-500"><div className="mx-auto flex max-w-[1440px] justify-between"><b className="text-xl text-slate-900">Bridge<span className="text-blue-600">Point</span></b><span>Work Today. Stronger Communities Tomorrow.</span></div></footer></div>;
}

function RolePicker({ role, setRole }: { role: Role; setRole: (role: Role) => void }) { return <div className="grid gap-2 md:grid-cols-3">{roles.map(([value, label, desc]) => <button type="button" key={value} onClick={() => setRole(value)} className={`rounded-xl p-3 text-left ${role === value ? "bg-blue-600 text-white" : "bg-slate-50 text-slate-700"}`}><b className="block text-sm">{label}</b><small className="mt-1 block text-[10px] opacity-80">{desc}</small></button>)}</div>; }

export function SignInPage() {
  const { login, logout } = useAuth(); const router = useRouter(); const searchParams = useSearchParams(); const requestedRole = searchParams.get("role"); const initialRole: Role = requestedRole === "worker" || requestedRole === "cooperative" ? requestedRole : "customer"; const [role, setRole] = useState<Role>(initialRole); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [show, setShow] = useState(false); const [remember, setRemember] = useState(true); const [error, setError] = useState(""); const [warning, setWarning] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(e: FormEvent) { e.preventDefault(); setError(""); setWarning(""); setLoading(true); try { const authenticatedUser = await login(email, password); const allowed = role === "cooperative" ? authenticatedUser.is_admin || authenticatedUser.roles?.includes("cooperative") : role === "worker" ? authenticatedUser.roles?.includes("labor") || authenticatedUser.role === "labor" || !!authenticatedUser.labor_category : authenticatedUser.is_admin || authenticatedUser.roles?.includes("employer") || (!authenticatedUser.roles?.length && authenticatedUser.role !== "labor"); if (!allowed && role !== "cooperative") { logout(); setError(`This account is not registered as a ${role}. Choose the correct role or create a matching account.`); return; } if (!allowed && role === "cooperative") { const message = "Demo access: This account is not registered as a cooperative. You can continue for demonstration purposes."; setWarning(message); if (typeof window !== "undefined") sessionStorage.setItem("bp_demo_role_warning", message); } setActiveWorkspaceRole(role); router.push(searchParams.get("next") || destination(role)); } catch (err: unknown) { setError(err instanceof Error ? err.message : "Sign in failed"); } finally { setLoading(false); } }
  return <Frame title={<>Welcome back.<br /><span className="bg-gradient-to-r from-blue-600 to-purple-500 bg-clip-text text-transparent">Build stronger communities.</span></>} text="Sign in to post jobs, find work, manage your cooperative, and access your benefits — all in one place."><h2 className="text-3xl font-bold">Sign In</h2><p className="mt-1 text-slate-500">Welcome back! Please enter your details to continue.</p><div className="mt-7"><RolePicker role={role} setRole={setRole} /></div><form onSubmit={submit} className="mt-7 space-y-5"><label className="block text-sm font-medium">Email<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required className="input-field mt-2" placeholder="Enter your email" /></label><label className="block text-sm font-medium">Password<div className="relative mt-2"><input type={show ? "text" : "password"} value={password} onChange={(e) => setPassword(e.target.value)} required className="input-field pr-14" placeholder="Enter your password" /><button type="button" onClick={() => setShow(!show)} className="absolute right-4 top-3 text-sm text-blue-600">{show ? "Hide" : "Show"}</button></div></label><div className="flex items-center justify-between text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={remember} onChange={(e) => setRemember(e.target.checked)} className="accent-blue-600" />Remember me</label><Link href="/forgot-password" className="text-blue-600">Forgot password?</Link></div>{warning && <p role="status" className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">{warning}</p>}{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={loading} className="w-full rounded-full bg-blue-600 py-4 font-semibold text-white">{loading ? "Signing In..." : "Sign In  →"}</button></form><div className="my-6 flex items-center gap-3 text-sm text-slate-400"><span className="h-px flex-1 bg-slate-200" />OR<span className="h-px flex-1 bg-slate-200" /></div><div className="grid grid-cols-2 gap-3"><button type="button" onClick={() => setError("Google sign-in is not connected yet.")} className="rounded-xl border py-3 text-sm">Continue with Google</button><button type="button" onClick={() => setError("Apple sign-in is not connected yet.")} className="rounded-xl border py-3 text-sm">Continue with Apple</button></div><p className="mt-8 text-center text-sm text-slate-500">Don&apos;t have an account? <Link href="/signup" className="font-semibold text-blue-600">Create account</Link></p></Frame>;
}

export function SignUpPage() {
  const { register, logout } = useAuth(); const router = useRouter(); const searchParams = useSearchParams(); const requestedRole = searchParams.get("role"); const initialRole: Role = requestedRole === "worker" || requestedRole === "cooperative" ? requestedRole : "customer"; const [role, setRole] = useState<Role>(initialRole); const [form, setForm] = useState({ name: "", email: "", phone: "", password: "", confirm: "" }); const [agree, setAgree] = useState(false); const [show, setShow] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const update = (key: string, value: string) => setForm((f) => ({ ...f, [key]: value }));
  async function submit(e: FormEvent) { e.preventDefault(); setError(""); if (form.password !== form.confirm) return setError("Passwords do not match."); if (!agree) return setError("Please accept the terms to continue."); setLoading(true); try { const registeredUser = await register({ full_name: form.name, email: form.email, phone: form.phone, password: form.password, role }); if (role === "cooperative" && !registeredUser.is_admin && !registeredUser.roles?.includes("cooperative")) { logout(); setError("Cooperative account creation was not approved."); return; } setActiveWorkspaceRole(role); router.push(searchParams.get("next") || destination(role)); } catch (err: unknown) { setError(err instanceof Error ? err.message : "Account creation failed"); } finally { setLoading(false); } }
  return <Frame title={<>Join the work that<br /><span className="bg-gradient-to-r from-blue-600 to-purple-500 bg-clip-text text-transparent">moves communities.</span></>} text="Create your BridgePoint account and find trusted work, workers, and cooperative opportunities."><h2 className="text-3xl font-bold">Create Account</h2><p className="mt-1 text-slate-500">Choose your role, then enter your details.</p><div className="mt-6"><RolePicker role={role} setRole={setRole} /></div><form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-sm font-medium">Name<input value={form.name} onChange={(e) => update("name", e.target.value)} required className="input-field mt-2" placeholder="Your full name" /></label><div className="grid gap-4 md:grid-cols-2"><label className="block text-sm font-medium">Email<input type="email" value={form.email} onChange={(e) => update("email", e.target.value)} required className="input-field mt-2" placeholder="you@example.com" /></label><label className="block text-sm font-medium">Phone<input value={form.phone} onChange={(e) => update("phone", e.target.value)} required className="input-field mt-2" placeholder="Your phone number" /></label></div><label className="block text-sm font-medium">Password<input type={show ? "text" : "password"} value={form.password} onChange={(e) => update("password", e.target.value)} required className="input-field mt-2" placeholder="Create a password" /></label><label className="block text-sm font-medium">Confirm Password<input type={show ? "text" : "password"} value={form.confirm} onChange={(e) => update("confirm", e.target.value)} required className="input-field mt-2" placeholder="Repeat your password" /></label><button type="button" onClick={() => setShow(!show)} className="text-sm text-blue-600">{show ? "Hide passwords" : "Show passwords"}</button><label className="flex items-start gap-2 text-sm text-slate-600"><input type="checkbox" checked={agree} onChange={(e) => setAgree(e.target.checked)} className="mt-1 accent-blue-600" />I agree to the BridgePoint terms and privacy policy.</label>{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={loading} className="w-full rounded-full bg-blue-600 py-4 font-semibold text-white">{loading ? "Creating Account..." : "Create Account  →"}</button></form><p className="mt-7 text-center text-sm text-slate-500">Already have an account? <Link href="/signin" className="font-semibold text-blue-600">Sign In</Link></p></Frame>;
}
