"use client";

import Link from "next/link";
import { useAuth } from "@/lib/auth-context";

const requests = [["Electrical Repair", "Ravi Kumar", "In progress", "₹1,200"], ["AC Servicing", "Meena Devi", "Scheduled", "₹900"], ["House Cleaning", "Arun Prakash", "Completed", "₹650"]];

export default function CustomerDashboard() {
  const { user, logout } = useAuth();
  return <div className="min-h-screen bg-[#f3f8ff] text-slate-900"><header className="border-b bg-white px-5 py-4"><div className="mx-auto flex max-w-6xl items-center justify-between"><Link href="/" className="text-2xl font-bold">Bridge<span className="text-blue-600">Point</span></Link><div className="flex items-center gap-4 text-sm"><span>⌖ Chennai</span><Link href="/find-services" className="text-blue-600">Find Workers</Link><button onClick={logout} className="text-red-600">Sign Out</button></div></div></header><main className="mx-auto max-w-6xl space-y-5 p-5 md:p-8"><section className="rounded-3xl bg-gradient-to-br from-white to-blue-50 p-7"><h1 className="text-3xl font-bold">Welcome back, {user?.full_name?.split(" ")[0] || "Customer"}!</h1><p className="mt-2 text-slate-600">Book trusted workers and keep every request in one place.</p><Link href="/post-job" className="mt-5 inline-block rounded-full bg-blue-600 px-6 py-3 font-semibold text-white">Book a Service →</Link></section><section className="grid gap-4 md:grid-cols-3">{[["3", "Active Requests"], ["₹2,750", "Total Payments"], ["4.8", "Your Rating"]].map(([value, label]) => <div key={label} className="rounded-2xl border bg-white p-5"><b className="text-3xl">{value}</b><p className="text-sm text-slate-500">{label}</p></div>)}</section><section className="rounded-3xl border bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold">Your Requests</h2><p className="text-sm text-slate-500">Track bookings, payments, and reviews.</p></div><Link href="/find-services" className="text-sm font-semibold text-blue-600">Find More Services →</Link></div><div className="mt-4 space-y-3">{requests.map(([title, worker, status, amount]) => <div key={title} className="flex flex-col gap-2 rounded-2xl bg-slate-50 p-4 sm:flex-row sm:items-center"><div className="flex-1"><b>{title}</b><p className="text-sm text-slate-500">Worker: {worker}</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs text-emerald-700">{status}</span><b>{amount}</b><div className="flex gap-2"><Link href="/payment" className="rounded-xl border border-blue-400 px-3 py-2 text-xs text-blue-600">Payment</Link><Link href="/reviews" className="rounded-xl border border-blue-400 px-3 py-2 text-xs text-blue-600">Review</Link></div></div>)}</div></section></main></div>;
}

