"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useState, useSyncExternalStore } from "react";
import { api } from "@/lib/api";
import { useAuth } from "@/lib/auth-context";
import type { Job } from "@/lib/types";

type Section = "jobs" | "earnings" | "skill-passport" | "training" | "messages" | "profile" | "settings";
const links = [["/worker", "Dashboard"], ["/jobs", "Available Jobs"], ["/worker/jobs", "My Jobs"], ["/worker/earnings", "Earnings"], ["/worker/skill-passport", "Skill Passport"], ["/worker/training", "Training & Welfare"], ["/worker/messages", "Messages"], ["/worker/profile", "Profile"], ["/worker/settings", "Settings"]] as const;

export default function WorkerFeaturePage({ section }: { section: Section }) {
  const { user, logout } = useAuth();
  const mounted = useSyncExternalStore(() => () => {}, () => true, () => false);
  const [jobs, setJobs] = useState<Job[]>([]);
  const [loading, setLoading] = useState(section === "jobs" || section === "earnings");
  const [error, setError] = useState("");
  const name = mounted ? (user?.full_name || "Worker") : "Worker";
  useEffect(() => {
    if (section !== "jobs" && section !== "earnings") return;
    let active = true;
    const request = section === "jobs" ? api.getActiveTasksAsLabor() : api.getLaborJobHistory();
    request.then((result) => { if (active) setJobs(result.jobs); }).catch((err: unknown) => { if (active) setError(err instanceof Error ? err.message : "Unable to load worker data."); }).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [section]);
  const title = section === "skill-passport" ? "Digital Skill Passport" : section === "training" ? "Training & Welfare" : section === "jobs" ? "My Jobs" : section === "earnings" ? "Earnings" : section[0].toUpperCase() + section.slice(1);
  return <div className="min-h-screen bg-[#f3f8ff] text-slate-900"><div className="flex"><aside className="hidden min-h-screen w-60 shrink-0 border-r bg-white p-5 lg:block"><Link href="/worker" className="text-2xl font-bold">Bridge<span className="text-blue-600">Point</span></Link><p className="mb-7 text-xs text-slate-500">Work that matters. People who care.</p><nav className="space-y-1">{links.map(([href, label]) => <Link key={href} href={href} className={`block rounded-xl px-3 py-3 text-sm ${href === `/worker/${section}` || (section === "jobs" && href === "/worker/jobs") ? "bg-blue-50 font-semibold text-blue-600" : "text-slate-700 hover:bg-slate-50"}`}>{label}</Link>)}</nav><button onClick={logout} className="mt-8 w-full rounded-xl border border-red-200 px-3 py-2 text-left text-sm text-red-600">Sign Out</button></aside><main className="min-w-0 flex-1"><header className="sticky top-0 z-20 flex items-center justify-between border-b bg-white/90 px-5 py-4 backdrop-blur"><Link href="/worker" className="text-xl font-bold lg:hidden">Bridge<span className="text-blue-600">Point</span></Link><div className="ml-auto flex items-center gap-4 text-sm"><span className="hidden md:block">⌖ Chennai</span><span>{name}</span><Link href="/worker/profile" className="text-blue-600">Profile</Link></div></header><div className="mx-auto max-w-6xl space-y-5 p-5 md:p-8"><div><p className="text-sm font-medium text-blue-600">BridgePoint / Worker</p><h1 className="mt-1 text-3xl font-bold">{title}</h1><p className="mt-1 text-slate-500">Your worker workspace, connected to your BridgePoint account.</p></div>{loading && <div className="rounded-2xl border bg-white p-6 text-slate-500">Loading your data...</div>}{error && <div className="rounded-2xl border border-red-200 bg-red-50 p-5 text-red-700"><b>Unable to load this section</b><p className="mt-1 text-sm">{error}</p><button onClick={() => window.location.reload()} className="mt-3 rounded-lg border border-red-300 px-3 py-2 text-sm">Retry</button></div>}{!loading && !error && section === "jobs" && <JobList jobs={jobs} empty="No accepted or active jobs found." />}{!loading && !error && section === "earnings" && <Earnings jobs={jobs} />}{section === "skill-passport" && <Passport user={user} />}{section === "training" && <Training />}{section === "messages" && <Empty title="Messages" text="Your worker messages will appear here when a conversation is available." />}{section === "profile" && <Profile user={user} />}{section === "settings" && <Empty title="Settings" text="Worker account settings are managed from your BridgePoint profile." />}</div></main></div></div>;
}

function JobList({ jobs, empty }: { jobs: Job[]; empty: string }) { return <section className="grid gap-4 md:grid-cols-2">{jobs.length === 0 ? <Empty title="My Jobs" text={empty} /> : jobs.map((job) => <article key={job.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-bold">{job.title}</h2><p className="text-sm text-slate-500">{job.city} · {job.date_of_task}</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs text-emerald-700">{job.status}</span></div><p className="mt-3 text-sm text-slate-600">{job.work_description}</p><div className="mt-4 flex items-center justify-between"><b>₹{job.worker_payout || job.budget}</b><Link href={`/jobs/${job.id}`} className="rounded-full border border-blue-400 px-4 py-2 text-sm text-blue-600">View Details</Link></div></article>)}</section>; }
function Earnings({ jobs }: { jobs: Job[] }) { const total = jobs.reduce((sum, job) => sum + (job.worker_payout || job.labor_receives || 0), 0); return <section className="space-y-4"><div className="grid gap-4 md:grid-cols-3"><Metric label="Recorded total" value={`₹${total.toLocaleString("en-IN")}`} /><Metric label="Completed jobs" value={String(jobs.filter((job) => job.status.includes("completed") || job.status === "payout_released").length)} /><Metric label="Transactions" value={String(jobs.length)} /></div><JobList jobs={jobs} empty="No earnings history is available yet." /></section>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border bg-white p-5 shadow-sm"><b className="text-2xl">{value}</b><p className="mt-1 text-sm text-slate-500">{label}</p></div>; }
function Passport({ user }: { user: ReturnType<typeof useAuth>["user"] }) { return <section className="grid gap-5 lg:grid-cols-[1fr_280px]"><div className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-4"><Image src="/hero-worker.svg" alt="Worker profile" width={110} height={110} className="h-24 w-24 rounded-2xl object-cover" /><div><h2 className="text-2xl font-bold">{user?.full_name || "Worker"}</h2><p className="text-slate-500">{user?.labor_category || "Verified worker"}</p><p className="mt-2 text-sm text-emerald-700">Identity and account verification status</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><p>✓ Identity status: {user?.email_verified ? "Verified" : "Pending"}</p><p>✓ Phone status: {user?.phone_verified ? "Verified" : "Pending"}</p><p>✓ Skills: {user?.skills?.join(", ") || "Not added yet"}</p><p>✓ Cooperative: Account membership status</p><p>✓ Insurance: Account status unavailable</p><p>✓ Credential model: Blockchain-ready architecture</p></div></div><div className="rounded-2xl border bg-white p-6 text-center shadow-sm"><Image src="/platform-qr.png" alt="Credential verification QR" width={150} height={150} className="mx-auto" /><p className="mt-3 text-sm text-slate-500">Credential verification interface</p></div></section>; }
function Training() { return <section id="benefits" className="grid gap-4 md:grid-cols-2"><Info title="Training programs" text="Browse cooperative-led skill improvement and certification programs." /><Info title="Welfare and insurance" text="Benefits and insurance status will appear here when connected to a provider." /><Info title="Certifications" text="Your verified certifications will be listed with the issuing organization." /><Info title="Cooperative support" text="Contact your cooperative for enrollment and benefit assistance." /></section>; }
function Profile({ user }: { user: ReturnType<typeof useAuth>["user"] }) { return <section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Worker Profile</h2><div className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><p>Name: {user?.full_name || "Not available"}</p><p>Email: {user?.email || "Not available"}</p><p>Phone: {user?.phone || "Not available"}</p><p>City: {user?.city || "Not available"}</p><p>Skills: {user?.skills?.join(", ") || "Not added yet"}</p><p>Bio: {user?.bio || "Not added yet"}</p></div></section>; }
function Info({ title, text }: { title: string; text: string }) { return <article className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">{title}</h2><p className="mt-2 text-sm text-slate-600">{text}</p></article>; }
function Empty({ title, text }: { title: string; text: string }) { return <section className="rounded-2xl border bg-white p-8 text-center shadow-sm"><h2 className="text-xl font-bold">{title}</h2><p className="mt-2 text-sm text-slate-500">{text}</p></section>; }
