"use client";

import Image from "next/image";
import Link from "next/link";

const services = ["Electrical Services", "Plumbing", "Carpentry", "Painting", "Cleaning", "Domestic Help", "Caregiver", "Driver", "Gardening", "Technician"];

export default function HomePage() {
  return (
    <div className="min-h-screen bg-[#f8fbff] text-[#0d1737]">
      <div className="bg-[#0874dc] px-5 py-2 text-xs text-white"><div className="mx-auto flex max-w-[1440px] items-center justify-between"><span>A cooperative-powered platform for stronger communities</span><span className="hidden md:block">English · தமிழ் · हिन्दी</span></div></div>
      <header className="border-b bg-white/95 px-5 py-4 shadow-sm"><div className="mx-auto flex max-w-[1440px] items-center gap-8"><Link href="/" className="text-2xl font-bold tracking-tight">Bridge<span className="text-[#0874dc]">Point</span></Link><nav className="hidden flex-1 items-center justify-center gap-8 text-sm md:flex"><Link className="border-b-2 border-blue-600 pb-5 text-blue-600" href="/">Home</Link><Link href="/signup">Find Services</Link><Link href="/signin?role=worker">For Workers</Link><Link href="/signin?role=cooperative">For Cooperatives</Link><a href="#about">About</a></nav><div className="ml-auto flex items-center gap-3"><Link href="/signin" className="text-sm text-slate-600">Sign In</Link><Link href="/signup" className="rounded-full bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white shadow-md">Get Started</Link></div></div></header>
      <main>
        <section className="relative overflow-hidden bg-gradient-to-br from-white via-[#f2f8ff] to-[#eef3ff] px-5 py-14"><div className="mx-auto grid max-w-[1440px] items-center gap-10 lg:grid-cols-[1.05fr_.95fr]"><div><div className="mb-5 inline-block rounded-full bg-[#e9eff8] px-4 py-2 text-xs text-slate-600">People · Skills · Stronger Communities</div><h1 className="max-w-2xl text-5xl font-bold leading-[1.05] tracking-tight md:text-7xl">Work that matters.<br /><span className="bg-gradient-to-r from-[#0874dc] via-[#386cf0] to-[#9b45d5] bg-clip-text text-transparent">People who care.</span></h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-slate-600">BridgePoint connects customers with cooperative workers in their city. Post a task, find skilled help, and manage the work through one accountable workspace.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/signup?role=customer&next=%2Fdashboard" className="rounded-full bg-blue-600 px-7 py-3.5 font-semibold text-white shadow-md">Book a Service →</Link><Link href="/post-job" className="rounded-full border border-blue-500 px-7 py-3.5 font-semibold text-blue-600">Post a Task</Link></div></div><div className="relative min-h-[400px]"><div className="absolute inset-8 rounded-[45%] bg-gradient-to-br from-blue-100 via-white to-indigo-100" /><div className="relative flex h-full min-h-[400px] items-center justify-center"><Image src="/hero-worker.svg" alt="BridgePoint cooperative worker illustration" width={410} height={410} className="relative z-10 h-[390px] w-auto drop-shadow-xl" priority /><div className="absolute right-0 top-0 z-20 max-w-56 rounded-3xl border bg-white p-4 shadow-xl"><b className="text-sm">Live workspace data</b><p className="mt-2 text-xs text-slate-500">Sign in to view verified workers, active jobs, and cooperative metrics from BridgePoint records.</p><Link href="/signin" className="mt-3 block rounded-xl bg-blue-50 p-2 text-center text-xs font-semibold text-blue-700">Open workspace</Link></div><div className="absolute bottom-0 left-0 right-8 z-20 rounded-3xl border bg-white p-4 shadow-xl"><b>🚨 Emergency Service?</b><p className="text-xs text-slate-500">Request help using a manually entered address.</p><Link href="/emergency" className="mt-2 inline-block rounded-full bg-red-50 px-4 py-2 text-xs font-semibold text-red-600">Request Emergency Help →</Link></div></div></div></div></section>
        <section className="border-y bg-white px-5 py-5"><div className="mx-auto grid max-w-[1440px] grid-cols-2 gap-5 md:grid-cols-5">{[["🛡️", "Verified Workers", "Verification status from worker records"], ["👥", "Cooperative Powered", "Supports local cooperative operations"], ["₹", "Secure Payments", "Recorded payment and payout flow"], ["♥", "Worker Welfare", "Support information when available"], ["★", "Reliable & Rated", "Reviews from completed work"]].map(([icon, title, desc]) => <div key={title} className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-blue-50 text-xl text-blue-600">{icon}</span><div><b className="text-sm">{title}</b><p className="text-xs text-slate-500">{desc}</p></div></div>)}</div></section>
        <section className="mx-auto max-w-[1440px] px-5 py-9"><div className="flex items-end justify-between"><div><h2 className="text-2xl font-bold">Popular Services</h2><p className="text-sm text-slate-500">Find trusted help for everyday needs</p></div><Link href="/signup?role=customer&next=%2Ffind-services" className="text-sm font-semibold text-blue-600">View All Services →</Link></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-5 lg:grid-cols-10">{services.map((service, i) => <Link key={service} href={`/signup?role=customer&next=${encodeURIComponent(`/find-services?service=${service}`)}`} className="rounded-2xl border bg-white p-4 text-center shadow-sm transition hover:-translate-y-1 hover:shadow-md"><span className="text-3xl">{["⚡", "💧", "🔨", "🖌️", "🧹", "⌂", "♥", "🚙", "🍃", "⚙️"][i]}</span><span className="mt-3 block text-xs font-medium">{service}</span></Link>)}</div></section>
        <section className="mx-auto grid max-w-[1440px] gap-4 px-5 pb-10 lg:grid-cols-3"><Feature title="Worker discovery" icon="AI" text="Search the live marketplace after signing in. Availability and job assignment come from BridgePoint records."><p className="rounded-2xl border bg-white p-4 text-sm text-slate-600">Worker profiles and service availability appear from the authenticated marketplace.</p><Link href="/signin?role=customer&next=%2Ffind-services" className="mt-4 inline-block text-sm font-semibold text-blue-600">Open Find Services →</Link></Feature><Feature title="Demand Forecast" icon="▥" text="Authorized cooperatives can review a data-driven forecast based on recorded BridgePoint job activity."><p className="rounded-2xl border bg-white p-4 text-sm text-slate-600">Forecast results are not presented as static public market data.</p><Link href="/signin?role=cooperative&next=%2Fadmin/demand-forecast" className="mt-5 inline-block rounded-full border border-blue-400 px-4 py-2 text-xs text-blue-600">Open Cooperative Insights →</Link></Feature><Feature title="Digital Skill Passport" icon="✓" text="Worker identity, skills, and certification status are shown from authenticated records."><p className="rounded-2xl border bg-white p-4 text-sm text-slate-600">Blockchain-ready credential architecture only. No on-chain credential or verification claim is made.</p><Link href="/signin?role=worker&next=%2Fworker/skill-passport" className="mt-4 inline-block rounded-full border border-blue-400 px-4 py-2 text-xs text-blue-600">Open Skill Passport →</Link></Feature></section>
        <section id="about" className="mx-auto grid max-w-[1440px] gap-4 px-5 pb-10 lg:grid-cols-2"><div className="relative min-h-64 overflow-hidden rounded-3xl bg-slate-900 shadow-lg"><Image src="/community-workers.svg" alt="BridgePoint cooperative workers" fill className="object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-slate-900/80 to-transparent" /><div className="relative flex h-full min-h-64 items-end p-7 text-white"><div><h2 className="max-w-xs text-3xl font-bold">Empowering<br />Skilled People.<br />Building Stronger<br />Communities.</h2><Link href="/signup?role=worker" className="mt-5 inline-block rounded-full bg-white px-5 py-2 text-sm font-semibold text-slate-900">Join as a Worker →</Link></div></div></div><div className="rounded-3xl bg-[#eef0ff] p-7"><h2 className="text-2xl font-bold">👥 For Cooperatives</h2><p className="mt-3 max-w-md text-sm leading-6 text-slate-600">Manage your workforce, review demand, allocate resources, and support members with connected BridgePoint tools.</p><Link href="/signup?role=cooperative" className="mt-5 inline-block rounded-full border border-blue-400 px-5 py-2 text-sm font-semibold text-blue-600">Access Cooperative Dashboard →</Link></div></section>
      </main>
      <footer className="bg-[#13243e] px-5 py-8 text-white"><div className="mx-auto flex max-w-[1440px] flex-col justify-between gap-5 text-sm md:flex-row"><div><b className="text-xl">Bridge<span className="text-blue-400">Point</span></b><p className="mt-2 text-xs text-slate-300">BridgePoint cooperative work infrastructure.</p></div><div className="flex flex-wrap gap-5 text-slate-300"><a href="#about">About</a><Link href="/signin?role=cooperative">Cooperatives</Link><a href="mailto:hello@bridgepoint.local">Contact</a><a href="#about">Privacy</a><a href="#about">Terms</a></div><span className="text-slate-300">India&apos;s work coordination platform</span></div></footer>
    </div>
  );
}

function Feature({ title, icon, text, children }: { title: string; icon: string; text: string; children: React.ReactNode }) { return <article className="rounded-3xl border bg-gradient-to-br from-white to-[#eff6ff] p-5 shadow-sm"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-100 font-bold text-blue-600">{icon}</span><h3 className="text-lg font-bold">{title}</h3></div><p className="mt-2 text-sm text-slate-600">{text}</p><div className="mt-5">{children}</div></article>; }
